#!/usr/bin/env python3
"""Lincoln MR / PR knowledge miner.

Extracts decision-related review comments from a merged pull request and writes
structured decision notes to the issue work package. These notes stay in
issue-<N>/docs/decisions/ until the sync-knowledge stage promotes them to
knowledge/.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

DECISION_KEYWORDS = ["decision", "decided", "agreed", "rejected", "note:", "approve", "approved"]


def _run_gh(args: list[str]) -> dict[str, Any] | list[Any]:
    """Call the gh CLI and return parsed JSON."""
    cmd = ["gh", *args]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or "gh CLI failed")
    return json.loads(result.stdout or "[]")


def _extract_decision_snippets(text: str) -> list[str]:
    """Pull decision-oriented sentences or paragraphs from a comment body."""
    if not text:
        return []
    snippets = []
    for paragraph in re.split(r"\n\s*\n", text.strip()):
        paragraph = paragraph.strip()
        if not paragraph:
            continue
        lowered = paragraph.lower()
        if any(keyword in lowered for keyword in DECISION_KEYWORDS):
            snippets.append(paragraph)
    return snippets


def _sanitize_filename(text: str) -> str:
    """Reduce a comment snippet to a safe filename slug."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    return text[:60]


def mine_pr_decisions(
    owner: str,
    repo: str,
    pr_number: int,
    issue_number: int | None = None,
    output_dir: Path | None = None,
) -> list[Path]:
    """Mine decision comments from a PR and write them to the issue package."""
    if output_dir is None:
        if issue_number is None:
            raise ValueError("issue_number or output_dir is required")
        output_dir = Path(f"issue-{issue_number}") / "docs" / "decisions"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    comments = _run_gh(
        ["api", f"repos/{owner}/{repo}/pulls/{pr_number}/comments"]
    )
    review_comments = _run_gh(
        ["api", f"repos/{owner}/{repo}/pulls/{pr_number}/reviews"]
    )

    if isinstance(comments, dict):
        comments = [comments]
    if isinstance(review_comments, dict):
        review_comments = [review_comments]

    all_comments = list(comments) + list(review_comments)

    written: list[Path] = []
    seen: set[str] = set()

    for comment in all_comments:
        body = comment.get("body") or ""
        snippets = _extract_decision_snippets(body)
        for snippet in snippets:
            if snippet in seen:
                continue
            seen.add(snippet)
            slug = _sanitize_filename(snippet)
            filename = f"pr-{pr_number}-{slug}.md"
            path = output_dir / filename
            if path.exists():
                continue

            content = f"""# PR {pr_number} Decision Note

**Source:** {owner}/{repo}#{pr_number}
**Author:** {comment.get('author', {}).get('login', 'unknown')}
**Created:** {comment.get('createdAt', 'unknown')}
**Comment ID:** {comment.get('id', 'unknown')}

## Snippet

{snippet}

## Keywords

{', '.join(DECISION_KEYWORDS)}

---
*Auto-generated by scripts/lincoln_mr_mine.py*
"""
            path.write_text(content, encoding="utf-8")
            written.append(path)

    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Mine PR review decisions")
    parser.add_argument("--owner", required=True)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--pr", type=int, required=True)
    parser.add_argument("--issue", type=int, default=None)
    parser.add_argument("--output-dir", type=Path, default=None)
    args = parser.parse_args(argv)

    paths = mine_pr_decisions(
        owner=args.owner,
        repo=args.repo,
        pr_number=args.pr,
        issue_number=args.issue,
        output_dir=args.output_dir,
    )
    for path in paths:
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
